### ISSUE TITLE
Can't open file presentation/script.vim

### ISSUE THREAD

**Issue by xautjzd** [tybenz/vimdeck#19]
I installed markdown syntax highlighting plugin(tpope/vim-markdown) and SyntaxRange plugin as README, but when I run `gem install vimdeck`, get errors as follow:

```
ERROR:  Error installing rmagick:
ERROR: Failed to build gem native extension.

/home/xautjzd/.rvm/rubies/ruby-2.0.0-head/bin/ruby extconf.rb
checking for Ruby version >= 2.0.0... yes
checking for gcc... yes
checking for Magick-config... no
Can't install RMagick 2.13.1. Can't find Magick-config i
...
```

after run `yum install ImageMagick-devel` and reinstall vimdeck, it's OK. So I think vimdeck may depend on  rmagick. will it be better to add it to README.?

after installing vimdeck successfully, I write a test.md file,it's content as follows:

```
## page1
page1


## page2
page2


## page3
page3
```

when finishing, I run `vimdeck test.md`, I get the error:

```
slide001.md 92L, 389C
Error detected while processing command line:
E484: Can't open file presentation/script.vim
```

but I can find presentation/script.vim in the same directory as test.md.Why?

**Comment by teto** [comment]
I had the same problem. I removed the "autochdir" option and it worked normally.
