### ISSUE TITLE
Problem detecting ImageMagick version

### ISSUE THREAD

**Issue by arathael** [tybenz/vimdeck#27]
I tried to install the gem but i stalled here:

![screen shot 2015-01-15 at 3 17 10](https://cloud.githubusercontent.com/assets/1380147/5755002/28aa4a6e-9c65-11e4-8e52-daff49314c5c.png)

**Comment by tybenz** [comment]
Looks like `brew install imagemagick` didn't quite work. 

Try running `convert --version` to see if it's in your path. If you get `command not found`, it didn't install correctly. You can try a fresh install, but it probably just didn't get moved into your path. Maybe try `brew link imagemagick`?

**Comment by arathael** [comment]
```
[ramram:~]$ convert --version
dyld: Library not loaded: /usr/local/lib/libpng16.16.dylib
  Referenced from: /usr/local/lib/libfreetype.6.dylib
  Reason: image not found
[1]    25648 trace trap  convert --version
[ramram:~]$ brew link imagemagick
Warning: Already linked: /usr/local/Cellar/imagemagick/6.9.0-3
To relink: brew unlink imagemagick && brew link imagemagick
[ramram:~]$ 
```

**Comment by tybenz** [comment]
Not sure what went wrong here... I'd try uninstalling and reinstalling imagemagick all over again.

```
brew uninstall imagemagick
brew install imagemagick
```

**Comment by arathael** [comment]
I'm still dealing with it, but I will close this because this may be env issue, not yours. Sorry.

**Comment by arathael** [comment]
Turned out to be Rmagick versioning, i followed [this instructions](http://stackoverflow.com/questions/28247947/fail-to-install-rmagick-on-mac-10-9-5) and built from source.

Then installing worked out fine.
