### ISSUE TITLE
All slides generated in one file when DOS line ending

### ISSUE THREAD

**Issue by pixelastic** [tybenz/vimdeck#29]
I'm trying to generate some slides from a markdown file, but all slides are generated in one `slide001.md` file instead of many.

After some digging, it seems that it is because of my `setlocal fileformat=dos` in my `after/ftplugin/markdown.vim`. 

I'm running ubuntu, but I like my markdown files to use a DOS line ending so they can more easily be shared (and diffed) with co-workers under windows.

**Comment by tybenz** [comment]
@pixelastic hey there. have you tried this in a while? is it working now?

**Comment by pixelastic** [comment]
I must say I switch to another tool to make my slides, and I don't remember if that specific issue was fixed. I'll have to give it a try. Still, I do not own a Windows machine so I might not be the best person to test :)

**Comment by tybenz** [comment]
Ok. Thanks. Closing for now. Will re-open if Windows users are still seeing this.
