### ISSUE TITLE
Can't use vimdeck

### ISSUE THREAD

**Issue by bsteindorf** [tybenz/vimdeck#34]
Everytime i start vimdeck i get this error message and i have no idea why:

/usr/lib/ruby/2.2.0/rubygems/dependency.rb:315:in `to_specs': Could not find 'artii' (~> 2.0.4) - did find: [artii-2.1.1] (Gem::LoadError)
Checked in 'GEM_PATH=/home/benedikt/.gem/ruby/2.2.0:/usr/lib/ruby/gems/2.2.0', execute `gem env` for more information
	from /usr/lib/ruby/2.2.0/rubygems/specification.rb:1311:in `block in activate_dependencies'
	from /usr/lib/ruby/2.2.0/rubygems/specification.rb:1300:in `each'
	from /usr/lib/ruby/2.2.0/rubygems/specification.rb:1300:in `activate_dependencies'
	from /usr/lib/ruby/2.2.0/rubygems/specification.rb:1282:in `activate'
	from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_gem.rb:67:in `block in gem'
	from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_gem.rb:66:in `synchronize'
	from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_gem.rb:66:in `gem'
	from /usr/lib/ruby/gems/2.2.0/bin/vimdeck:22:in `<main>'

**Comment by tybenz** [comment]
Looks like `artii`, one of vimdeck's dependencies didn't install correctly.

Try (might need to put sudo in front of these):

```shell
gem uninstall vimdeck
gem install vimdeck
```

Let me know what output you see when you do that.

**Comment by tybenz** [comment]
Closing for now. Will re-open if you're still seeing the issue.
