### ISSUE TITLE
Can't install on on OSX

### ISSUE THREAD

**Issue by mhartington** [tybenz/vimdeck#36]
I'm getting an error trying to install vimdeck on osx, 10.10.3.

Imagemagick version: 6.9.1-6
Ruby version: 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]

```bash
sudo gem install vimdeck
```
The error output this log
https://gist.github.com/mhartington/21feb682034deab83076

Any ideas?

**Comment by tybenz** [comment]
I've been stumped on this as well. It seems like an issue with the rmagick/asciiart native extensions. I put a temporary build without the asciiart gem up here: https://rubygems.org/gems/vimdeck-without-ascii-art.

Install with `sudo gem install vimdeck-without-ascii-art`

You still get figlet/ascii headers, but it won't do anything with images. Hope that helps for now...

Will hopefully find time to troubleshoot this later and get it working on OS X once again.

**Comment by marioidival** [comment]
Syntax Highlight don't work with `vimdeck-without-ascii-art`?

**Comment by tybenz** [comment]
@mhartington try installing latest version of vimdeck (https://github.com/tybenz/vimdeck/releases/tag/v0.3.0). should be working once again.

@marioidival that was an issue with both versions. i need to make the README clearer about a new dependency of SyntaxRange, called [ingo-library](https://github.com/vim-scripts/ingo-library). Add this to your vim install, and Syntax Range should work for you.

**Comment by marioidival** [comment]
@tybenz So, don't work...

**Comment by tybenz** [comment]
@marioidival sorry. did you try adding the new dependency to your vimrc and it *still* isn't working?

**Comment by mhartington** [comment]
Sorry for not replying. Everything seems to work fine now :+1:

**Comment by tybenz** [comment]
@mhartington Not a problem. I see you work at Drifty. I worked with Max a little bit on jquery mobile stuff a few years ago. Ionic looks amazing. Will definitely try it out soon!
