### ISSUE TITLE
change figlet font for headings

### ISSUE THREAD

**Issue by sq6jnx** [tybenz/vimdeck#37]
Hi,

is it possible to change `figlet` font used for headings? Say, what if I'd like to use smkeyboard for h2?

If it is not yet possible I'd suggest possibility to define vimdeck options inside `.mdown` file (but possibly this is anoter issue...).

**Comment by tybenz** [comment]
This should be possible with `vimdeck -h smkeyboard` or `vimdeck --header-font smkeyboard`.

https://github.com/tybenz/vimdeck/compare/2d50d2ec594a8c448c8eec649e40b2c981b53a65...f3a3ea2deac540754eefa591eedd1aed588425b7
