### ISSUE TITLE
Unable to install on macOS Sierra

### ISSUE THREAD

**Issue by ngriffin7a** [tybenz/vimdeck#48]
@tybenz I saw some commits that indicated you might be doing development on a mac. Do you have any hints as to how to get vimdeck installed on macOS Sierra? RMagick does not install correctly. Thank you.

**Comment by caarlos0** [comment]
I was able to fix it with:

```
brew install imagemagick@6
PKG_CONFIG_PATH=/usr/local/opt/imagemagick@6/lib/pkgconfig gem install vimdeck
```

**Comment by ngriffin7a** [comment]
That worked, thanks @caarlos0

**Comment by tybenz** [comment]
Moving these instructions into README

**Comment by tybenz** [comment]
Done: https://github.com/tybenz/vimdeck/commit/e79e0723f81c968b8978ca4393231e958b6731b5

Thanks y'all 👍

**Comment by kyleholzinger** [comment]
FWIW, the current instructions don't include the setting of `PKG_CONFIG_PATH`, which I had to do in order to get this to work :/

**Comment by tybenz** [comment]
@kyleholzinger could you open a PR with updated instructions that include this step?
